#
# Module manifest for module 'Docker.PowerShell.CLI'
#
# Generated by: Caleb Frederickson
#
# Generated on: 5/4/2023
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule    = 'debugmodule.psm1'

    # Version number of this module.
    ModuleVersion = '0.0.1'

    # ID used to uniquely identify this module
    GUID          = '8edbbcb3-cdb3-4d86-9bb7-43b5fc69c08d'

    # Author of this module
    Author        = 'Caleb Frederickson'

    # Company or vendor of this module
    CompanyName   = 'Kenai Peninsula Borough School District'

    # Copyright statement for this module
    Copyright     = '(c) Caleb Frederickson. All rights reserved.'

    # Description of the functionality provided by this module
    Description   = 'PowerShell wrapper for docker CLI'

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData   = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            LicenseUri = 'https://opensource.org/license/mit'

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Prerelease string of this module
            Prerelease = 'debug'

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''
}

